### ISSUE TITLE
Type of sign?

### ISSUE THREAD

**Issue by shemethy** [EugeneFeingold/ArduinoDigitalSignController#1]
Any information at all on what type of sign this code is for?

**Comment by EugeneFeingold** [comment]
The sign doesn't have any identifying characteristics that could let me simply tell you a brand and model. It's just a black metal box with a 128x16 red led array (made up of 8x8 pixel blocks). 

However the software it came with seemed pretty generic, with features like color that my sign didn't support, so I think that it works with a large number of these anonymous Chinese signs that are controllable over a serial port. 

Attached are a few photos of what mine looks like.

 Good luck!

**Comment by EugeneFeingold** [comment]
Of course the attachments didn't come through via email... 

![image 1](https://cloud.githubusercontent.com/assets/1341787/2818267/ec3f775c-cee2-11e3-8c0f-03931aae695a.jpeg)

![image 2](https://cloud.githubusercontent.com/assets/1341787/2818266/ec3f1bd6-cee2-11e3-9937-421ab7c0d678.jpeg)

**Comment by shemethy** [comment]
Thanks Eugene, that is super helpful. 

I will need to get the rs232 cable. I like the idea of ethernet control.
